#Reference: https://youtu.be/XhY-VdmSIUQ

In [1]:
!pip install git+https://github.com/Joeclinton1/google-images-download.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/Joeclinton1/google-images-download.git to /tmp/pip-req-build-xhrn6uh8
  Running command git clone -q https://github.com/Joeclinton1/google-images-download.git /tmp/pip-req-build-xhrn6uh8
     |████████████████████████████████| 981 kB 5.2 MB/s 
     |████████████████████████████████| 138 kB 47.9 MB/s 
     |████████████████████████████████| 358 kB 54.8 MB/s 
     |████████████████████████████████| 55 kB 4.2 MB/s 
     |████████████████████████████████| 4.0 MB 28.0 MB/s 
     |████████████████████████████████| 58 kB 5.8 MB/s 
  Created wheel for google-images-download: filename=google_images_download-2.8.0-py2.py3-none-any.whl size=15965 sha256=d14e331a4a8fc6b7052be3c694ecc24401a282dd2000ed8688c8d30a4b287fe5
  Stored in directory: /tmp/pip-ephem-wheel-cache-n9m0vpge/wheels/79/5c/d2/2569a4f55ff29b3c4d6b1114d5110a70a79afbf381e6eb3e87
Successfully built google-imag

In [2]:
from google_images_download import google_images_download
response = google_images_download.googleimagesdownload()

In [3]:
!git clone --depth 1 https://github.com/tensorflow/models

Cloning into 'models'...
remote: Enumerating objects: 3403, done.
remote: Counting objects: 100% (3403/3403), done.
remote: Compressing objects: 100% (2828/2828), done.
remote: Total 3403 (delta 897), reused 1419 (delta 518), pack-reused 0
Receiving objects: 100% (3403/3403), 34.95 MiB | 21.71 MiB/s, done.
Resolving deltas: 100% (897/897), done.


In [4]:
%%bash
cd models/research/
protoc object_detection/protos/*.proto --python_out=.
cp object_detection/packages/tf2/setup.py .
python -m pip install .

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Processing /content/models/research
  Created wheel for object-detection: filename=object_detection-0.1-py3-none-any.whl size=1694828 sha256=b588cf20a6639eb3e21be25764aa7699a26fc9a886129bb01c02ae9e4afe1625
  Stored in directory: /tmp/pip-ephem-wheel-cache-juvqxikd/wheels/fa/a4/d2/e9a5057e414fd46c8e543d2706cd836d64e1fcd9eccceb2329
  Created wheel for py-cpuinfo: filename=py_cpuinfo-8.0.0-py3-none-any.whl size=22257 sha256=96c946b1a9eea8849ae9c51cd782468f4c5d29d8b787def7a0b9df17c468e010
  Stored in directory: /root/.cache/pip/wheels/d2/f1/1f/041add21dc9c4220157f1bd2bd6afe1f1a49524c3396b94401
  Created wheel for dill: filename=dill-0.3.1.1-py3-none-any.whl size=78544 sha256=5cccddab53158a7c40f5c9a71a7f225bc38bd40602b00fd3bc7d49e71023d1e2
  Stored in directory: /root/.cache/pip/wheels/a4/61/fd/c57e374e580aa78a45ed78d5859b3a44436af17e22ca53284f
  Created wheel for avro-python3: filename=avro_p

  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
selenium 4.3.0 requires urllib3[secure,socks]~=1.26, but you have urllib3 1.25.11 which is incompatible.
multiprocess 0.70.13 requires dill>=0.3.5.1, but you have dill 0.3.1.1 which is incompatible.
gym 0.17.3 requires cloudpickle<1.7.0,>=1.2.0, but you have cloudpickle 2.1.0 which is incompatible.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.28.0 which is incompatible.
datascience 0.10.6 requires fol

In [5]:
import numpy as np
from six import BytesIO
from PIL import Image, ImageDraw, ImageFont
from IPython.display import display, Javascript
from IPython.display import Image as IPyImage
import glob
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline
from object_detection.utils import visualization_utils as viz_utils
from object_detection.utils import colab_utils

In [6]:
import tensorflow as tf

In [7]:
from google.colab import drive
from google.colab import files
drive.mount('/content/drive')

Mounted at /content/drive


In [8]:
#Function to create each image into a numpy array
def load_image_into_numpy_array(path):
  img_data = tf.io.gfile.GFile(path, 'rb').read()
  image = Image.open(BytesIO(img_data))
  (im_width, im_height) = image.size
  return np.array(image.getdata()).reshape((im_height, im_width, 3)).astype(np.uint8)

In [16]:
path = "/content/drive/MyDrive/Data Sets - Colab/UTS Thesis/Face - real, drawing, not a face/train/Other Object/*"
hidden_images_np = []
for iname in glob.glob(path):
  hidden_images_np.append(load_image_into_numpy_array(iname))


In [17]:
gt_boxes = []
colab_utils.annotate(hidden_images_np, box_storage_pointer=gt_boxes)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

'--boxes array populated--'

<IPython.core.display.Javascript object>

In [18]:
gt_boxes

[array([[0.00273437, 0.015625  , 0.95606771, 0.953125  ]]),
 array([[0.23273437, 0.078125  , 0.86773437, 0.8203125 ]]),
 array([[0.00106771, 0.00390625, 0.88106771, 1.        ]]),
 array([[0.04773438, 0.046875  , 0.99606771, 0.93359375]]),
 array([[0.06940104, 0.07421875, 0.78440104, 0.8984375 ]]),
 array([[0.24106771, 0.08984375, 0.97106771, 0.82421875]]),
 array([[0.50440104, 0.51953125, 0.97273437, 0.93359375]]),
 array([[0.12440104, 0.03515625, 0.82273438, 0.99609375]]),
 array([[0.39273438, 0.18359375, 0.72773438, 0.828125  ]]),
 array([[0.24440104, 0.1484375 , 0.82940104, 0.81640625]]),
 array([[0.15940104, 0.09375   , 0.77106771, 0.734375  ]]),
 array([[0.35440104, 0.2265625 , 0.72940104, 0.6953125 ]]),
 array([[0.32940104, 0.00390625, 0.82773438, 0.99609375]]),
 array([[0.40940104, 0.3359375 , 0.78773438, 0.65625   ]]),
 array([[0.18440104, 0.171875  , 0.90606771, 0.87109375]]),
 array([[0.27940104, 0.12890625, 0.92106771, 0.8359375 ]]),
 array([[0.30940104, 0.3671875 , 0.55273

In [19]:
np.save('weights', gt_boxes)

In [20]:
type(gt_boxes)

list

In [22]:
#Convert list to np.array
arr = np.array(gt_boxes)
arr.shape

#convert array to df
m,n,r = arr.shape
out_arr = np.column_stack((np.repeat(np.arange(m),n),arr.reshape(m*n,-1)))
df = pd.DataFrame(out_arr)

#Download df as csv
df.to_csv('weights.csv') 
files.download('weights.csv')

(268, 1, 4)

In [28]:
#Df to xml file
def to_xml(df): 
    mode='w'
    filename=None
    def row_to_xml(row):
        xml = ['<item>']
        for i, col_name in enumerate(row.index):
            xml.append('  <field name="{0}">{1}</field>'.format(col_name, row.iloc[i]))
        xml.append('</item>')
        return '\n'.join(xml)
    res = '\n'.join(df.apply(row_to_xml, axis=1))

    if filename is None:
        return res
    with open(filename, mode) as f:
        f.write(res)



In [33]:
"""
#print (to_xml(df))
df_xml = to_xml(df)
df_xml.to_xml('wts.xml') 
files.download('wts.xml')
"""

"\n#print (to_xml(df))\ndf_xml = to_xml(df)\ndf_xml.to_xml('wts.xml') \nfiles.download('wts.xml')\n"